version: '3.1'

services:
  app:
    image: ghcr.io/anton-dealmeida/fyyur-artist-website:latest
    restart: always
    ports:
      - "5000:5000"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      PG_DB_HOSTNAME: "db"
      DEBUG: "True"
      PORT: 5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password123!"
      POSTGRES_DB: "fyyur-db"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
